codecov:
  token: 789fe774-c57c-447b-b8d2-f7e6012629e7

comment:
  layout: header, changes, diff
  
coverage:
  precision: 2
  round: nearest
  
  ignore:
  - tests/.*

  status:
    project:
      default:
        target: auto
        if_no_uploads: error

    patch:
      default:
        if_no_uploads: error

    changes: true

  parsers:
    gcov:
      branch_detection:
        macro: no
        loop: no
        conditional: yes
        method: no

