name: Build

on: [push, pull_request]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: check
      uses: actions/checkout@v1
    - name: valgrind-install
      run: sudo apt-get install -y valgrind
    - name: build
      run: mkdir -p build && cd build && cmake .. && make && make test
  release:
    runs-on: ubuntu-latest
    steps:
    - name: check
      uses: actions/checkout@v1
    - name: valgrind-install
      run: sudo apt-get install -y valgrind
    - name: build
      run: mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=release -DENABLE_TESTS=ON -DENABLE_VALGRIND_TESTS=ON .. && make && make test

